version: "3"

services:
  nginx:
    image: nginx:1.13.12
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/tmp:/var/log/nginx:rw
    ports:
      - 80:80
    networks:
      - frontend
      - backend
#    deploy:
#      replicas: 2

#  logstash:
#    build:
#      context: logstash/
#    image: multi-container-php-application/logstash
#    volumes:
#      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
#      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
#    ports:
#      - 5044
#    environment:
#      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
#    depends_on:
#      - elasticsearch
#    networks:
#      - backend

networks:
  frontend:
  backend:
